Give dynamically generated instructions on how to replicate errors during the build progress
This works by storing the current step at all times in a global Mutex
and registering an `at_exit` handler which looks up the current step.

- Allow overriding the path shown per-step
- Override the path for the `Crate` step
- Add `--stage` to the suggestion
- Suggest `src/test/ui` instead of the name of the source directory
- Suggest `--test-args` if present

Example output for check:

```
Checking stage0 rustdoc artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Checking rustdoc v0.0.0 (/home/joshua/rustc/src/librustdoc)
error: expected item, found `/`
 --> src/librustdoc/lib.rs:1:1
  |
1 | /
  | ^ expected item

error: aborting due to previous error

error: could not compile `rustdoc`

To learn more, run the command again with --verbose.
command did not execute successfully: "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "check" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "8" "--release" "--manifest-path" "/home/joshua/rustc/src/tools/rustdoc/Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit status: 101
note: failed while building bootstrap::check::Rustdoc
help: to replicate this failure, run `./x.py check src/librustdoc`
failed to run: /home/joshua/rustc/build/bootstrap/debug/bootstrap check src/librustdoc
Build completed unsuccessfully in 0:00:01
```

Example output for tests:

```
note: failed while building bootstrap::test::Compiletest
help: to replicate this failure, run `./x.py test src/test/ui --stage 1`
```